### ISSUE TITLE
using tracing_subscriber results in crash

### ISSUE THREAD

**Issue by happylinks** [h7kanna/temporal-rust-worker#1]
Hey!

Thanks for the repo, wanted to try temporal with rust and this works great :)

I'm running into an error when I'm trying to add a tracing_subscriber to main:
```
2023-08-03T13:49:37.795039Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [2, 4, 16, 16, 9, 14, 7, 7] }
2023-08-03T13:49:37.797449Z DEBUG next_workflow_activation{task_queue=default run_id="395bef9c-13cf-4c96-a97f-9645464d29f6"}: temporal_sdk_core::worker::workflow: Sending activation to lang activation=WorkflowActivation(run_id: 395bef9c-13cf-4c96-a97f-9645464d29f6, is_replaying: true, jobs: StartWorkflow)
thread '<unnamed>' panicked at 'tried to drop a ref to Id(4), but no such span exists!', /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:350:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:350:21
   3: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:186:12
   4: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:186:12
   5: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:186:12
   6: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:186:12
   7: <alloc::sync::Arc<S> as tracing_core::subscriber::Subscriber>::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/subscriber.rs:856:9
   8: tracing_core::dispatcher::Dispatch::try_close
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:705:9
   9: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::exit::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:303:52
  10: tracing_core::dispatcher::get_default::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:397:24
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/thread/local.rs:270:16
  12: tracing_core::dispatcher::get_default
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:394:5
  13: <tracing_subscriber::registry::sharded::Registry as tracing_core::subscriber::Subscriber>::exit
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/registry/sharded.rs:303:17
  14: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::exit
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:162:9
  15: <tracing_subscriber::layer::layered::Layered<L,S> as tracing_core::subscriber::Subscriber>::exit
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.17/src/layer/layered.rs:162:9
  16: tracing_core::dispatcher::Dispatch::exit
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-core-0.1.31/src/dispatcher.rs:638:9
  17: tracing::span::Span::do_exit
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1054:13
  18: <tracing::span::Entered as core::ops::drop::Drop>::drop
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/span.rs:1568:9
  19: core::ptr::drop_in_place<tracing::span::Entered>
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ptr/mod.rs:497:1
  20: temporal_sdk_core::worker::workflow::workflow_stream::WFStream::build_internal::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/workflow/workflow_stream.rs:166:21
  21: <T as futures_util::fns::FnMut1<A>>::call_mut
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/fns.rs:28:9
  22: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:59:33
  23: core::option::Option<T>::map
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/option.rs:1075:29
  24: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:59:21
  25: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/map.rs:58:26
  26: <futures_util::stream::stream::Inspect<St,F> as futures_core::stream::Stream>::poll_next
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/lib.rs:102:13
  27: <futures_util::stream::stream::take_while::TakeWhile<St,Fut,F> as futures_core::stream::Stream>::poll_next
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/take_while.rs:80:47
  28: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/mod.rs:1632:9
  29: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/stream/stream/next.rs:32:9
  30: temporal_sdk_core::worker::workflow::Workflows::new::{{closure}}::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/workflow/mod.rs:220:56
  31: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:923:42
  32: tokio::task::local::LocalSet::with::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:684:13
  33: std::thread::local::LocalKey<T>::try_with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/thread/local.rs:270:16
  34: std::thread::local::LocalKey<T>::with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/thread/local.rs:246:9
  35: tokio::task::local::LocalSet::with
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:667:9
  36: <tokio::task::local::RunUntil<T> as core::future::future::Future>::poll
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:913:9
  37: tokio::task::local::LocalSet::run_until::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:573:19
  38: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
  39: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:57
  40: tokio::runtime::coop::with_budget
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  41: tokio::runtime::coop::budget
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  42: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:651:25
  43: tokio::runtime::scheduler::current_thread::Context::enter
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:410:19
  44: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:650:36
  45: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:68
  46: tokio::runtime::context::scoped::Scoped<T>::set
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/scoped.rs:40:9
  47: tokio::runtime::context::set_scheduler::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:26
  48: std::thread::local::LocalKey<T>::try_with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/thread/local.rs:270:16
  49: std::thread::local::LocalKey<T>::with
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/thread/local.rs:246:9
  50: tokio::runtime::context::set_scheduler
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context.rs:176:9
  51: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:729:27
  52: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:638:19
  53: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:175:28
  54: tokio::runtime::context::runtime::enter_runtime
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  55: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/current_thread.rs:167:9
  56: tokio::runtime::runtime::Runtime::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:311:47
  57: tokio::task::local::LocalSet::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/task/local.rs:534:9
  58: temporal_sdk_core::worker::workflow::Workflows::new::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/workflow/mod.rs:199:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-08-03T13:49:37.994477Z  INFO next_workflow_activation{task_queue=default}: temporal_sdk_core::worker: Initiated shutdown task_queue=default namespace=default
2023-08-03T13:49:37.994745Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(21), error_code: CANCEL }
2023-08-03T13:49:37.994769Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(7), error_code: CANCEL }
2023-08-03T13:49:37.994781Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(19), error_code: CANCEL }
2023-08-03T13:49:37.994791Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(17), error_code: CANCEL }
2023-08-03T13:49:37.994801Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(9), error_code: CANCEL }
2023-08-03T13:49:37.994810Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(3), error_code: CANCEL }
2023-08-03T13:49:37.994890Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(5), error_code: CANCEL }
2023-08-03T13:49:37.994904Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(11), error_code: CANCEL }
2023-08-03T13:49:37.994915Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(23), error_code: CANCEL }
2023-08-03T13:49:37.994927Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=Reset { stream_id: StreamId(15), error_code: CANCEL }
2023-08-03T13:49:37.994973Z  INFO temporal_sdk: Removing workflow from cache run_id=395bef9c-13cf-4c96-a97f-9645464d29f6
2023-08-03T13:49:37.995258Z  INFO temporal_sdk: Polling loops exited
thread 'main' panicked at 'Workflow processing terminates cleanly: Error joining workflow processing thread: Any { .. }', /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/mod.rs:409:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::expect
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1033:23
   4: temporal_sdk_core::worker::Worker::shutdown::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/mod.rs:406:9
   5: <temporal_sdk_core::worker::Worker as temporal_sdk_core_api::Worker>::shutdown::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/core/src/worker/mod.rs:180:25
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/future/future.rs:125:9
   7: temporal_sdk::Worker::run::{{closure}}
             at /Users/michielwesterbeek/.cargo/git/checkouts/sdk-core-cf0016372e610028/6c61e03/sdk/src/lib.rs:333:39
   8: temporal_rust_worker::main::{{closure}}
             at ./src/main.rs:70:18
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:63
  10: tokio::runtime::coop::with_budget
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on
             at /Users/michielwesterbeek/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:313:45
  18: temporal_rust_worker::main
             at ./src/main.rs:74:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-08-03T13:49:38.001753Z DEBUG tower::buffer::worker: buffer closing; waking pending tasks
[Finished running. Exit status: 101]
^[[1;2D
```

This is the code I'm using:
```let env_filter = tracing_subscriber::EnvFilter::from_default_env();
    tracing_subscriber::registry()
        .with(env_filter)
        .with(fmt::Layer::default())
        .try_init()?;
 ```
        
Do you have any idea what could be causing this?

**Comment by h7kanna** [comment]
Hi, 
This repo is just a demo and uses my custom SDK fork (which does not have a stable API figured out at all). 
Having said that, I need to investigate the telemetry configuration.

**Comment by happylinks** [comment]
No worries, I understand! Was just curious if you came across the same problem. I'll dig deeper into the problem as well. I know this is not stable and very experimental, but are you aware of any problems I should keep in mind from your tests with it?

**Comment by h7kanna** [comment]
I was waiting for the open telemetry dependency to be updated to the latest in the SDK. It is now.
 I will retest with tracing-subscriber enabled and keep you posted.
